---
- name: '[Build Image] Get updated files from git repository'
  git:
    repo: "https://{{ DOCKERFILE_GIT_URL }}:{{ DOCKERFILE_GIT_PASS }}@{{ DOCKERFILE_GIT_USER }}"
    dest: "{{ DOWNLOAD_PATH }}/{{ SERVICE_NAME }}"
    accept_hostkey: yes

- name: '[Download Artifact] Download artifacts from Nexus'
  get_url:
    url: "{{ NEXUS_BASE_URL }}/service/local/artifact/maven/content?r={{ NEXUS_REPOSITORY }}&g={{ ARTIFACT_GROUP }}&a={{ ARTIFACT_ID }}&p={{ ARTIFACT_TYPE }}&v={{ ARTIFACT_VERSION }}"
    dest: "{{ DOWNLOAD_PATH }}/{{ SERVICE_NAME }}"
