---
#Intenta cambiar el proyecto.

- name: '[Cambiar Proyecto] Cambia proyecto'
  command: "{{ OC_CLIENT_PATH }}/oc project  easytravel"
  register: result
  ignore_errors: True
#Intenta escarlar el pod

- name: '[Escalar pod] Escalando el pod'
  command: "{{ OC_CLIENT_PATH }}/rc scale --replicas=3 dc easytravel-www"
  register: result
  ignore_errors: True
