---
#Intenta escalar un pod y  registra en  result
#Openshift client is expected to be already available on the OC_CLIENT_PATH

- name: '[Elegir el Proyecto] pasarse al proyecto coolstore'
  command: "{{ OC_CLIENT_PATH }}/oc project 'coolstore'"
  
- name: '[Escala un pod] escala el pod de coolstore'
  command: "{{ OC_CLIENT_PATH }}/oc scale --replicas=3 dc web-ui"
 register: result
  ignore_errors: True

